### ISSUE TITLE
Credit and derivatives

### ISSUE THREAD

**Issue by ITR13** [creditstxt/credit-requirement#15]
The license feels a bit unclear on how the license has to be handled by different forms of derivatives, and whether or not it applies to both source and software, or just the software itself. 

If somebody modifies source that uses these credit requirements, are they required to give credit where the source is accessible, or only when compiled and distributed that way?

Does derivative software also need to use these requirements if the license these requirements were added to requires derivatives to use the same license? And what if the license doesn't propagate?

If somebody properly credits a software or service, then somebody else bundles that software or service, does the bundler also have to give credit?

**Comment by kemitchell** [comment]
These terms affect the license terms for the software. If what you do with the software requires a license, the combination of license and these terms requires giving credit.

**Comment by ioistired** [comment]
> If somebody properly credits a software or service, then somebody else bundles that software or service, does the bundler also have to give credit?

Hmm, interesting. The GPLv3 has a clause about what happens if you just redistribute software unmodified using P2P networks:

> You are not required to accept this License in order to receive or
run a copy of the Program.  Ancillary propagation of a covered work
occurring solely as a consequence of using peer-to-peer transmission
to receive a copy likewise does not require acceptance.

It's not quite the same case though. I think for bundling, it depends on what you mean by that. If "bundling" involves taking software A which uses credits requirement and, say, including it in a Linux distribution, then it should be obvious that the bundler has to give credit since they are distributing the code. I had an idea for a moment that "bundling" could somehow include making a new service based on the code of two other services, but I can't think of an example that doesn't count as making a derivative work and therefore triggering the license exception.

In my eyes it's safe to close this issue. @kemitchell leave it open if you disagree.
